### Index
GET http://localhost:3000/api/v1/study_plans

### Show
GET http://localhost:3000/api/v1/study_plans/2

### Create
POST http://localhost:3000/api/v1/study_plans
Content-Type: application/json

{
    "title": "The Challenging Challenge",
    "points": "1200",
    "studyDaysString": "0111111",
    "startDate": "2021-03-12",
    "endDate": "2021-04-30"
}

### Update
PUT http://localhost:3000/api/v1/study_plans/2
Content-Type: application/json

{
    "title": "Ultra Ninja Warrior",
    "points": 300,
    "studyDaysString": "0010111",
    "startDate": "2021-03-26",
    "endDate": "2021-06-26"
}

### Destroy
DELETE http://localhost:3000/api/v1/study_plans/6

### Start Fresh
POST http://localhost:3000/api/v1/study_plans/start_fresh
Content-Type: application/json

{
    "id": 1
}