### Index
GET http://localhost:3000/api/v1/subtasks

### Show
GET http://localhost:3000/api/v1/subtasks/1

### Create
POST http://localhost:3000/api/v1/subtasks
Content-Type: application/json

{
    "studyTaskId": "3",
    "point": "1"
}

### Update
PUT http://localhost:3000/api/v1/subtasks/1
Content-Type: application/json

{
    "studyTaskId": "3",
    "point": "3"
}

### Destroy
DELETE http://localhost:3000/api/v1/subtasks/2
